### ISSUE TITLE
 Add support for reading `config.json` in the `refresh_data` script #5 Open *WIP*

### ISSUE THREAD

**Issue by rummankarim** [mottaquikarim/airgo#12]
Currently testing docker on the laptop and also making changes to see what works or doesn't.

**Comment by rummankarim** [comment]
@mottaquikarim  You see this correct? This is how you open a pull request?

**Comment by mottaquikarim** [comment]
@rummankarim no this is not how you open a pull request. Go back to the video we recorded together for proper guidelines. Or, google around for a tutorial.

Also, increasing space available on docker: https://docs.docker.com/docker-for-mac/space/

**Comment by mottaquikarim** [comment]
You should also try the following:

```
# Delete every Docker containers
# Must be run first because images are attached to containers
docker rm -f $(docker ps -a -q)

# Delete every Docker image
docker rmi -f $(docker images -q)
```

More details here:
https://blog.baudson.de/blog/stop-and-remove-all-docker-containers-and-images
