### ISSUE TITLE
Baby's first PR *WIP*

### ISSUE THREAD

**Issue by mottaquikarim** [mottaquikarim/airgo#4]
1. Clone this repo
2. Read the README and ensure you are able to get the make targets working as expected
3. Create a new branch: `git checkout -b rumman/first-pr`
4. Update README and add yourself (and myself) under a new subsection (at the bottom) called **CONTRIBUTORS**.
5. Each name should link to the person's github repo
6. Push your branch (google this if unsure) and open a PR and add me to it.

**Comment by mottaquikarim** [comment]
Some resources from our conversation:

* [Git Basics](https://www.freecodecamp.org/news/learn-the-basics-of-git-in-under-10-minutes-da548267cc91/)
* [Docker](https://docker-curriculum.com/)
* [Docker Slides](https://show.zohopublic.com/publish/9alge85d4a29cb4d94a74a80cda42ca9351b5)

**Comment by mottaquikarim** [comment]
## Setting up SSH Keys Github

1. First, [generate SSH key](https://docs.github.com/en/enterprise/2.15/user/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)
2. Then, [add to your account](https://docs.github.com/en/enterprise/2.15/user/articles/adding-a-new-ssh-key-to-your-github-account)
3. Finally, ensure you can push a commit to github from command line

**Comment by rummankarim** [comment]
Okay no problem.
